#!/bin/bash
#SBATCH --job-name=TestRunSOM
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16000
#SBATCH --time=3:00:00
#SBATCH --output=job_Roefer.out
#SBATCH --error=job_Roefer.err
#SBATCH --mail-user=stu241428@mail.uni-kiel.de
#SBATCH --mail-type=ALL
#SBATCH --partition=base

module load gcc12-env/12.3.0
module load miniconda3/24.11.1
conda activate venv
python src/python/SelfOrgMap/minisom_test.py
conda deactivate

jobinfo